export type MainStackParamList = {
  WorkspacesList: undefined;
  CreateWorkspace: undefined;
  WorkspaceDetail: { workspaceId: string };
  SearchWorkspaces: undefined;
  MyJoinRequests: undefined;
  IncomingJoinRequests: { workspaceId: string };
  GenerateInvite: { workspaceId: string };
  JoinByCode: undefined;
  CubesList: { workspaceId: string };
  CreateCube: { workspaceId: string };
  CubeDetail: { cubeId: string };
  EditCube: { cubeId: string };
  VenuesList: { workspaceId: string };
  CreateVenue: { workspaceId: string };
  EditVenue: { venueId: string };
  EventsList: { workspaceId: string };
  CreateEvent: { workspaceId: string };
  EventDetail: { eventId: string };
  EditEvent: { eventId: string };
  EventCheckIn: { eventId: string };
  PairingsList: { eventId: string };
  PairingDetail: { pairingId: string };
  CubeRoulette: { eventId: string };
  LifeTracker: { matchId: string };
  MatchResult: { matchId: string };
  Standings: { eventId: string };
};
